/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.coffeetechgaff.storm.algorithmnode;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum NodeStatus {
  TESTING, PRODUCTION, RETIRED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"NodeStatus\",\"namespace\":\"com.coffeetechgaff.storm.algorithmnode\",\"symbols\":[\"TESTING\",\"PRODUCTION\",\"RETIRED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
